### PR TITLE
Batch requests

### PR DESCRIPTION
**Pull request by Intrepidd**

### CODE REVIEW

**Comment by jarthod** [comment]
Nice !
Could you please add a spec for when 2 requests are batched, because here you only have 1 or 2 in 2 requests, no 2+ in 1 requests.

**Comment by Intrepidd** [comment]
Yes, I thought about doing that but never actually did it, good point.

**Comment by jarthod** [comment]
Seems great otherwise. Promise all the things !

**Comment by Intrepidd** [comment]
I just added this new spec

**Comment by jarthod** [comment]
Cool :)

**Comment by jarthod** [comment]
This has been merged

**Pull request closed without merging**
